### ISSUE TITLE
TypeError: plot_summary() got an unexpected keyword argument 'd'

### ISSUE THREAD

**Issue by kuning19901** [PyDMD/PyDMD#480] opened 2023-12-23 08:25 UTC
When I am trying to test the examples, the following error abouth plot_summary() occurs, could I know how to fix it?

TypeError                                 Traceback (most recent call last)
<ipython-input-12-c6d13e8d26d4> in <module>
      2 delay_dmd = hankel_preprocessing(dmd, d=delays)
      3 delay_dmd.fit(Xn.T)
----> 4 plot_summary(delay_dmd, d=delays)
      5 
      6 print(

TypeError: plot_summary() got an unexpected keyword argument 'd'

**Comment by fandreuz** [comment] 2023-12-24 08:27
Hi @kuning19901, could you please tell us the output of `pip show pydmd`? The problem could be caused by an outdated version of PyDMD.

**Comment by kuning19901** [comment] 2023-12-24 15:00
> Hi @kuning19901, could you please tell us the output of `pip show pydmd`? The problem could be caused by an outdated version of PyDMD.

Hi, @fandreuz , many thanks for your reply. I have found the reason for that. It should be the problem of the version. This problem exists when I use the code from https://github.com/PyDMD/PyDMD. If I use the code from https://github.com/mathLab/PyDMD, the problem disappears. I think the plot_summary() should be different for these two sources.

**Comment by fandreuz** [comment] 2024-01-08 21:50
Hi @kuning19901, sorry for the delay. Are you sure it is not the other way around? I mean, https://github.com/PyDMD/PyDMD should have the new option (https://github.com/PyDMD/PyDMD/blob/master/pydmd/plotter.py#L542) and https://github.com/mathLab/PyDMD should not have it (https://github.com/mathLab/PyDMD/blob/master/pydmd/plotter.py#L535). The latter is an unmaintained fork that we rarely update

**Comment by fandreuz** [comment] 2024-03-05 21:06
Closing since we did not receive replies after 2 months, please feel free to reopen the issue if it is still relevant

**Closed as completed by fandreuz** 2024-03-05 21:06 UTC
